### ISSUE TITLE
Increase Code Coverage

### ISSUE THREAD

**Issue by JHartzer** [suneeshjacob/ACRoD#3]
Excellent work on the unit tests. They are certainly a step in the right direction. My concern is they are simply checking for the original output and therefore don't share very much information. Additionally changes in the function output would be difficult to diagnose. Moving towards checking each array element one at a time would be more clear. Using a package like [unittest](https://docs.python.org/3/library/unittest.html) could also assist you as it has built-in functions for checking if output is near to an expected result.

Running [coverage.py](https://coverage.readthedocs.io/en/7.3.2/#) shows good coverage of `functions.py` at 86%. The main paths missing are all the `'descending'` options, `joint_type == 6`, and `joint_type == 7`. Getting those testing would put the package at nearly 100% code coverage.

**Comment by suneeshjacob** [comment]
Thanks for the suggestions. I added two more examples covering helical and plane joints (i.e., `joint_type == 6` and `joint_type == 7`). I will work on the remaining ones (i.e., `'descending'` and unittests) and will update about them.

**Comment by suneeshjacob** [comment]
I added a few functions covering `descending` and now coverage.py is showing the coverage of `functions.py` at 98%.

**Comment by suneeshjacob** [comment]
@JHartzer Regarding checking output, each test function checks both the output string and also the jacobian matrix for a random set of dimensional parameters of the robot at a random end-effector point (by using `numpy.isclose`. The output string comparison is to ensure that the symbolic matrix functions for Jacobian are being generated properly, and the other comparison is to ensure numerical values of jacobian matrix for a given pose. So, both numerical and symbolic results are tested in the tests and they include comparison of the entire matrices, which include individual comparisons as well, as they would pass the tests only if individual elements are close enough. Is a separate comparison of individual elements of matrices still required?

**Comment by JHartzer** [comment]
I'm glad to hear you were able to increase the code coverage and test the additional joint types. Regarding your question, I think it is a good practice to check in such a way that if you change your code and a test fails, it is clear what has failed. However, if you don't foresee the output changing drastically, then I don't think you should go through the effort of refactoring these tests and can consider this issue closed with the increased code coverage.

**Comment by suneeshjacob** [comment]
Hi, I now made changes in the tests to let it print - whenever there is a mismatch in a numpy matrix - the row and column indices where the first mismatch is found, so as to make it easier for developers to debug any mismatch between expected and computed values. Thanks for your suggestion.

With this, I am closing this issue.
