### ISSUE TITLE
Community Guidelines

### ISSUE THREAD

**Issue by CameronDevine** [suneeshjacob/ACRoD#7]
As part of the JOSS review (openjournals/joss-reviews#5927) I have not found any community guidelines for,

1. contributing to the software,
2. reporting issues or problems, and
3. seeking support.

**Comment by suneeshjacob** [comment]
I now added community guidelines at the bottom of [README.md](https://github.com/suneeshjacob/ACRoD/blob/main/README.md).

**Comment by CameronDevine** [comment]
@suneeshjacob, this looks perfect.
