### ISSUE TITLE
Statement of Need

### ISSUE THREAD

**Issue by CameronDevine** [suneeshjacob/ACRoD#8]
The only documentation I have found so far is the [README.md](README.md) file. As part of the JOSS review (openjournals/joss-reviews#5927) this documentation should include a statement of need. I did not find anything I would consider a statement of need in the Readme.

**Comment by suneeshjacob** [comment]
Yes, the documentation is currently only in [README.md](https://github.com/suneeshjacob/ACRoD/issues/README.md) file (and the full API documentation is aimed for future version). And I am already planning to add more examples based on `[gfadini](https://github.com/gfadini)`'s review. A statement of need was included in the paper but was not included in the documentation. It is now included in the [README.md](https://github.com/suneeshjacob/ACRoD/issues/README.md) file, thanks for pointing that out.

**Comment by CameronDevine** [comment]
Thank you for including the statement of need in the documentation @suneeshjacob.
